### ISSUE TITLE
Identificar y describir interesados

### ISSUE THREAD

**Issue by JakoPapaFrita** [JakoPapaFrita/equipo4_IJFR_ppi2020#4]
[Identificacion.interesados.docx](https://github.com/JakoPapaFrita/equipo4_IJFR_ppi2020/files/4833523/Identificacion.interesados.docx)

**Comment by asdarkdark** [comment]
[Identificación interesados.docx](https://github.com/JakoPapaFrita/equipo4_IJFR_ppi2020/files/4747454/Identificacion.interesados.docx)
