### ISSUE TITLE
Realizar diagrama de espina de pescado

### ISSUE THREAD

**Issue by JakoPapaFrita** [JakoPapaFrita/equipo4_IJFR_ppi2020#6]
![Altos costes y pocos sitios para visitar en medelling (1)](https://user-images.githubusercontent.com/66627447/86139764-bbc02480-bab5-11ea-8c62-604e8d973605.png)

**Comment by SamuelGarciaCorrea** [comment]
![Diagrama espina de pescado](https://user-images.githubusercontent.com/66627447/84046134-4f974880-a96f-11ea-97cb-f47cbaf7596d.jpg)
