### ISSUE TITLE
Realizar validación con al menos 5 usuarios

### ISSUE THREAD

**Issue by JakoPapaFrita** [JakoPapaFrita/equipo4_IJFR_ppi2020#8]
[Validación de Usuarios 1° Cuadrante.pdf](https://github.com/JakoPapaFrita/equipo4_IJFR_ppi2020/files/4833501/Validacion.de.Usuarios.1.Cuadrante.pdf)

**Comment by Offztinger** [comment]
[Validación de Usuarios 1° Cuadrante.pdf](https://github.com/JakoPapaFrita/equipo4_IJFR_ppi2020/files/4833475/Validacion.de.Usuarios.1.Cuadrante.pdf)
