### ISSUE TITLE
Hacer tablero de visión del producto

### ISSUE THREAD

**Issue by JakoPapaFrita** [JakoPapaFrita/equipo4_IJFR_ppi2020#9]
Describir la visión del producto: Es un proyecto para los extranjeros que tienen una mala experiencia en cuestión de turismo en Medellín, se llama “ViajesPaisa” y es una página web que permitirá mostrar los lugares turísticos de la ciudad, restaurantes y hoteles cercanos a cada sitio turístico a diferencia de buscar cada lugar turístico de Medellín en diferentes páginas web que no tienen toda la información de estos, nuestro producto será en inglés y en español, ahorrándole tiempo y esfuerzo de traducir o no comprender el idioma, además de no buscar cada sitio de la ciudad el cual quieran visitar, brindándole a los extranjeros una mejor comodidad que otras páginas no les pueden ofrecer con tan solo un clic.

**Comment by asdarkdark** [comment]
Describir la visión del producto: Es un proyecto para los extranjeros que tienen una mala experiencia en cuestión de turismo en Medellín, se llama “ViajesPaisa” y es una página web que permitirá mostrar los lugares turísticos de la ciudad, restaurantes y hoteles cercanos a cada sitio turístico a diferencia de buscar cada lugar turístico de Medellín en diferentes páginas web que no tienen toda la información de estos, nuestro producto será en inglés y en español, ahorrándole tiempo y esfuerzo de traducir o no comprender el idioma, además de no buscar cada sitio de la ciudad el cual quieran visitar, brindándole a los extranjeros una mejor comodidad que otras páginas no les pueden ofrecer con tan solo un clic.
